---
title: "possum_age"
author: "Yuzheng Wang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_library, echo=FALSE}
# install.packages("tidyverse")
# import library
library(dplyr)
library(tidyverse)
library(MASS)
```


```{r load_possums_data, echo=FALSE}
data_path <- "Dataset/possums.csv"
origin_possums_data <- read.csv(data_path)
```

```{r init_plot, echo=FALSE}
data_plot <- ggplot(origin_possums_data, aes(x = totlngth, y = age)) +
  geom_point() +
  labs(title = "年龄 vs 总长度（负鼠）",
       x = "总长度",
       y = "年龄") +
  theme_minimal()
data_plot
```

There is 7 sites in the dataset, after one-hot encoding, if site1 to site6 are all zero, that means the possum is come from site7.

```{r process_possums_data, echo=FALSE}
# remove col
possums_data <- origin_possums_data %>% dplyr::select(-c(case, Pop))

# One-hot encode the 'site' variable and remove the original 'site' variable
possums_data <- possums_data %>%
  mutate(
    site1 = ifelse(site == '1', 1, 0),
    site2 = ifelse(site == '2', 1, 0),
    site3 = ifelse(site == '3', 1, 0),
    site4 = ifelse(site == '4', 1, 0),
    site5 = ifelse(site == '5', 1, 0),
    site6 = ifelse(site == '6', 1, 0)
  ) %>%
  dplyr::select(-site)

# set sex to female and make the data 0 ~ 1
possums_data <- possums_data %>%
  mutate(
    female = ifelse(sex == 'f', 1, 0)
  ) %>%
  dplyr::select(-sex)

# separate data to train-test-val 80%-10%-10%
set.seed(222)
data_count <- nrow(possums_data)
train_ind <- sample(1:data_count, size = data_count * 0.8)

# Subset the training set
possums_data_train <- possums_data[train_ind, ]

# Create a temporary dataset for the remaining data
remaining_data <- possums_data[-train_ind, ]
# Split the remaining data into test (10%) and validation (10%) sets
test_ind <- sample(1:nrow(remaining_data), size = nrow(remaining_data) * 0.5)

possums_data_test <- remaining_data[test_ind, ]
possums_data_val <- remaining_data[-test_ind, ]
```


```{r stepwise_feature_select}
# Full model with all predictors
features <- c("female", "hdlngth", "skullw", "totlngth", "taill", "footlgth", "earconch", "eye", "chest", "belly")

p <- 0

best_features <- vector(length = length(features) +1)

MSE_train_best <- vector(length = length(features) +1)

MSE_valid_best <- vector(length = length(features) +1)

predictor <- c("1")

# concatenate the response with the predictor to generate the formula
formula <- paste("age ~", predictor, sep = " ")

# use lm() to find the model
fit_models <- lm(formula = formula, data = possums_data_train)

# find the MSE
MSEs_train <- mean((fit_models$residuals)^2)

# store the minimum MSE, only one value at stage though
MSE_train_best[1] <- min(MSEs_train)

# find the MSE on validation set
MSE_valid_best[1] <- mean((predict(fit_models, newdata = possums_data_val) - possums_data_val$age)^2)
best_features[1] <- predictor

p <- 1

# generate all combinations of features, take p at a time, return the result as a list
predictor <- combn(features, p, simplify = FALSE)

# generate formula respectively
formula <- sapply(predictor, function(x) paste("age", "~", paste0(x, collapse = "+"), sep = " "))

# generate model respectively
fit_models <- lapply(formula, function(x) lm(x, data = possums_data_train))

# get the MSE respectively
MSEs_train <- sapply(1:length(fit_models), function(x) mean(fit_models[[x]]$residuals^2))

best_features[1 + p] <-predictor[[which.min(MSEs_train)]]

# stored the smallest MSE
MSE_train_best[1 + p] <- min(MSEs_train)  

# find out the best performed feature and store its MSE on validation set
MSE_valid_best[1 + p] <- mean((predict(fit_models[[which.min(MSEs_train)]], newdata = possums_data_val) - possums_data_val$age)^2)

for (i in 2 :length(features)) {
  p = i
  predictor <- Filter(function(x) all(best_features[2:p]  %in% x), combn(features, p, simplify = FALSE))
  formula <- sapply(predictor, function(x) paste("age", "~", paste0(x, collapse = "+"), sep = " "))

  fit_models <- lapply(formula, function(x) lm(x, data = possums_data_train))

  MSEs_train <- sapply(1:length(fit_models), function(x) mean(fit_models[[x]]$residuals^2))
  best_features[1 + p] <- setdiff(predictor[[which.min(MSEs_train)]],best_features[2:p] )
  
  MSE_train_best[1 + p] <- min(MSEs_train)
  print(which.min(MSEs_train))
  
  MSE_valid_best[1 + p] <- mean((predict(fit_models[[which.min(MSEs_train)]], newdata = possums_data_val) - possums_data_val$age)^2)
  print(MSE_valid_best)
}
```

```{r}
df_MSE <- data.frame(feature=ordered(best_features, levels = unique(best_features)), MSE_training = MSE_train_best, MSE_valid = MSE_valid_best)

# knitr::kable(df_MSE, align = "ccc")
```

```{r}
ggplot(data=df_MSE, aes(x=feature)) +
  geom_point(aes(y=MSE_training, color="MSE_training")) +
  geom_line(aes(y=MSE_training, color="MSE_training", group=1)) +
  geom_point(aes(y=MSE_valid, color="MSE_validate")) + 
  geom_line(aes(y=MSE_valid, color="MSE_validate", group=1)) +
  geom_point(aes(y=min(MSE_valid), x=feature[which.min(MSE_valid)]), size = 5, color = "black", shape = 13) + 
  labs(x="Features in order", y="MSE")
```




